CREATE DATABASE Smart_Wallet;

USE Smart_Wallet;

CREATE TABLE incomes(
    id INT PRIMARY KEY AUTO_INCREMENT,
    montant FLOAT NOT NULL,
    description varchar(1000) NOT NULL,
    date_ DATE DEFAULT (CURRENT_TIME)
);
CREATE TABLE expences(
    id INT PRIMARY KEY AUTO_INCREMENT,
    montant FLOAT NOT NULL,
    description varchar(1000) NOT NULL,
    date_ DATE DEFAULT (CURRENT_TIME)
);
ALTER TABLE incomes ADD dateIn DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE expences ADD dateIn DATETIME DEFAULT CURRENT_TIMESTAMP;

TRUNCATE incomes;

CREATE TABLE users(
    userId INT PRIMARY KEY AUTO_INCREMENT,
    userName varchar(256),


);
